### PR TITLE
ignition-setup-user: for DM boot-device get path from lsblk, instead of using /dev/disk/by-label/boot

### PR DESCRIPTION
**Pull request by nikita-dubrovskii**
Signed-off-by: Nikita Dubrovskii <nikita@linux.ibm.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
We're having a debate about multipath over in https://github.com/coreos/ignition-dracut/issues/154 - it'd be good if you were able to join and sync up!

**Comment by cgwalters** [comment]
There's also https://github.com/coreos/ignition-dracut/pull/158 here

**Comment by nikita-dubrovskii** [comment]
> There's also #158 here

I tried it with `qemu+multipath`, but it didn't work

**Comment by darkmuggle** [comment]
@nikita-dubrovskii we have move ignition-dracut into ignition itself. But I think this is obsolete? If so can you either move this ignition or close this out?

**Comment by bgilbert** [comment]
Closing this out, since this repository is abandoned.  Please reopen against [coreos/ignition](https://github.com/coreos/ignition) if still relevant.

**Pull request closed without merging**
