### PR TITLE
ignition: fix correct device path when randomizing UUID

### PR DESCRIPTION
**Pull request by tuan-hoang1**
The correct path is /dev/disk/by-label/root.

Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>

### CODE REVIEW

**Comment by tuan-hoang1** [comment]
Confirmed working on s390x.

**Comment by ajeddeloh** [comment]
They're both correct. partlabel is created using the partition label ans label is created using the filesystem label. Was partlabel not working on s390x?

**Comment by tuan-hoang1** [comment]
This is the output I get from `/dev/disk/by-*` : https://tpaste.us/DLdo

And output from `sgdisk` in `create_disk.sh`: https://tpaste.us/BoZy

**Comment by ajeddeloh** [comment]
I don't follow. Both should be symlinks created by udev that point to the same place.

**Comment by tuan-hoang1** [comment]
It smells like big endian issue to me.
`''$'\344\224\200\344\230\200\344\244\200\342\264\200\345\214\200\345\244\200\345\214\200\345\220\200\344\224\200\344\264\200'` should be string `EFI-SYSTEM`. @sharkcz: wdyt ?

**Comment by ajeddeloh** [comment]
This looks like maybe a systemd-udev bug or udev rules bug? We can switch to `label` since it doesn't matter which we use.

**Comment by dustymabe** [comment]
> They're both correct. partlabel is created using the partition label ans label is created using the filesystem label. Was partlabel not working on s390x?

still would be nice to know if there is a bug there in s390x - can someone else confirm? @sharkcz @jcajka

**Comment by sharkcz** [comment]
I think partlabel doesn't exist for DASDs.

**Comment by dustymabe** [comment]
interesting.. So using partlabel won't work for s390x?

I wonder if we need to change any other code. Looks like mantle uses it in a few places.

**Comment by arithx** [comment]
@dustymabe The only place that `by-partlabel` is used in mantle is on CL specific tests.

**Comment by dustymabe** [comment]
+1 - thanks @arithx

**Comment by tuan-hoang1** [comment]
@sharkcz : regarding the decoding thing, I think it's an endian bug in gptfdisk.

```
sfdisk -d metal.disk
...
... name="\xe6\x88\x80\xe6\xbc\x80\xe6\xbc\x80\xe7\x90\x80"
... name="\xe7\x88\x80\xe6\xbc\x80\xe6\xbc\x80\xe7\x90\x80"
...
```
```
python -c "print(repr('\xe7\x88\x80\xe6\xbc\x80\xe6\xbc\x80\xe7\x90\x80'.decode('utf8')))"
u'\u7200\u6f00\u6f00\u7400'
```
Those must be reverse byte order of unicode string '72 6f 6f 74' of 'root'.

**Comment by tuan-hoang1** [comment]
Bingo:

https://github.com/tuan-hoang1/gptfdisk/blob/master/gptpart.cc#L201
https://github.com/tuan-hoang1/gptfdisk/blob/master/parttypes.h#L6

**Comment by cgwalters** [comment]
> https://github.com/tuan-hoang1/gptfdisk/blob/master/gptpart.cc#L201

OT: I see that kind of C code and am amazed that it doesn't have even more bugs.  It's the kind of C code that if I maintained it I'd be rewriting in Rust...

**Comment by tuan-hoang1** [comment]
I think we just need to define `USE_UTF16` and use `#include <unicode/ustream.h>` instead. Checking ...

**Comment by tuan-hoang1** [comment]
My very narrow investigation says GPT savse partition name in little endian format  (`https://en.wikipedia.org/wiki/GUID_Partition_Table : "56 (0x38) 72 bytes Partition name (36 UTF-16LE code units) "`). So if the underlying data is decided that way, we could either :
1. Make the partition name field to be mixed endian format (how? change the spec? lol )
2. Do the endian conversion when reading from disk (i.e. `sfdisk -d metal.raw`). But that would mean we have to fix udev and every downstream application that read those LE data without endian conversion.

**Comment by tuan-hoang1** [comment]
so tl;dr GPT partition name field (`name=` output from `sfdisk -d`) is not usable on s390x atm.

**Pull request merged**
