### PR TITLE
WIP [spec2x] Don't teardown network in initramfs

### PR DESCRIPTION
**Pull request by vrutkovs**
This breaks bonding configuration via kernel args. This is not required for master branch, as FCOS uses NM configs instead of ifcfgs.

Previously admins were encouraged to setup `ip=` kernel arg and add ifcfg files in Ignition. Any difference in these configs could cause networking to be misconfigured, so in #78 initramfs networking was being torn down and new settings were applied.

This is no longer necessary, as `ip` and other network kernel args are being persisted, so custom Ignition modifications for static networking are no longer required. Also there should be no difference in initramfs networking and first boot networking setup by ifcfgs, as these use the same `ip=` kernel arguments.  Any difference between kargs config and persisted config would be dracut bug imo.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1758091

TODO:
* [ ] Ensure this don't break RHCOS tests
* [ ] Ensure this doesn't break openshift install
* [ ] Ensure static IP can still be persisted via kargs

### CODE REVIEW

**Comment by cgwalters** [comment]
Worth noting this reverts https://github.com/coreos/ignition-dracut/pull/78

**Comment by cgwalters** [comment]
So, binding is about reliability, but at install and/or "Ignition boot" I think it'd generally be fine to use one interface.

So another approach is to just document that users who want to use bonding should use [coreos.no_persist_ip](https://github.com/coreos/ignition-dracut/pull/89) with `ip=` for a single underlying physical interface, and specify the bonding configuration via Ignition, so it's used for all subsequent boots.

**Comment by cgwalters** [comment]
If we're reverting something, generally we should look at the rationale for the previous change, and describe why it no longer applies.

Unfortunately, the rationale in https://github.com/coreos/ignition-dracut/pull/78 isn't too detailed.  My recollection is that e.g. we wanted to support a case where a user has specified DHCP during the Ignition phase, but static IPs defined via Ignition thereafter?

**Comment by vrutkovs** [comment]
>My recollection is that e.g. we wanted to support a case where a user has specified DHCP during the Ignition phase, but static IPs defined via Ignition thereafter?

Updated the description. Not sure if "DHCP on Ignition phase and static IP later on" case would work - NetworkManager falls back to ifcfgs if no other config source (e.g. DHCP) has been found IIRC. I'll test that usecase as well with this PR

**Comment by yuqi-zhang** [comment]
Context: https://bugzilla.redhat.com/show_bug.cgi?id=1693428

**Comment by vrutkovs** [comment]
Less intrusive solution - https://github.com/coreos/ignition-dracut/pull/123

**Pull request closed without merging**
